spring.application.name=mitglieder-backend-test
server.port=0

spring.datasource.url=jdbc:mariadb://192.168.178.63:3306/emc_mitglieder_test
spring.datasource.username=emc_backend_test_rw
spring.datasource.password=Nissi#1968+24010605
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.flyway.enabled=false

logging.level.root=INFO
logging.level.de.emc.mitglieder=INFO